@hostname = localhost
@port = 8000
@host = {{hostname}}:{{port}}
@contentType = application/json

###
GET http://{{host}}/movie?search=cordoba HTTP/1.1
Content-Type: {{contentType}}

###

GET http://{{host}}/movie HTTP/1.1
Content-Type: {{contentType}}

###

GET http://{{host}}/user/1/movies HTTP/1.1
Content-Type: {{contentType}}

###
# TMBN sample request
GET https://api.themoviedb.org/3/movie/550?api_key={{API_KEY_V3}} HTTP/1.1
Content-Type: {{contentType}}

